/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface Result : NSObject <TBase, NSCoding> {
  int32_t __ret;
  NSString * __msg;

  BOOL __ret_isset;
  BOOL __msg_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=ret, setter=setRet:) int32_t ret;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
#endif

- (id) init;
- (id) initWithRet: (int32_t) ret msg: (NSString *) msg;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) ret;
- (void) setRet: (int32_t) ret;
#endif
- (BOOL) retIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

@end

@interface UserBean : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __name;
  double __allMoney;
  double __availableMoney;
  double __blockedMoney;
  int32_t __loginTimes;
  double __todayCost;
  double __todayWin;
  int32_t __score;
  int32_t __msgNum;
  NSString * __key;

  BOOL __id_isset;
  BOOL __name_isset;
  BOOL __allMoney_isset;
  BOOL __availableMoney_isset;
  BOOL __blockedMoney_isset;
  BOOL __loginTimes_isset;
  BOOL __todayCost_isset;
  BOOL __todayWin_isset;
  BOOL __score_isset;
  BOOL __msgNum_isset;
  BOOL __key_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=allMoney, setter=setAllMoney:) double allMoney;
@property (nonatomic, getter=availableMoney, setter=setAvailableMoney:) double availableMoney;
@property (nonatomic, getter=blockedMoney, setter=setBlockedMoney:) double blockedMoney;
@property (nonatomic, getter=loginTimes, setter=setLoginTimes:) int32_t loginTimes;
@property (nonatomic, getter=todayCost, setter=setTodayCost:) double todayCost;
@property (nonatomic, getter=todayWin, setter=setTodayWin:) double todayWin;
@property (nonatomic, getter=score, setter=setScore:) int32_t score;
@property (nonatomic, getter=msgNum, setter=setMsgNum:) int32_t msgNum;
@property (nonatomic, retain, getter=key, setter=setKey:) NSString * key;
#endif

- (id) init;
- (id) initWithId: (int32_t) id name: (NSString *) name allMoney: (double) allMoney availableMoney: (double) availableMoney blockedMoney: (double) blockedMoney loginTimes: (int32_t) loginTimes todayCost: (double) todayCost todayWin: (double) todayWin score: (int32_t) score msgNum: (int32_t) msgNum key: (NSString *) key;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) allMoney;
- (void) setAllMoney: (double) allMoney;
#endif
- (BOOL) allMoneyIsSet;

#if !__has_feature(objc_arc)
- (double) availableMoney;
- (void) setAvailableMoney: (double) availableMoney;
#endif
- (BOOL) availableMoneyIsSet;

#if !__has_feature(objc_arc)
- (double) blockedMoney;
- (void) setBlockedMoney: (double) blockedMoney;
#endif
- (BOOL) blockedMoneyIsSet;

#if !__has_feature(objc_arc)
- (int32_t) loginTimes;
- (void) setLoginTimes: (int32_t) loginTimes;
#endif
- (BOOL) loginTimesIsSet;

#if !__has_feature(objc_arc)
- (double) todayCost;
- (void) setTodayCost: (double) todayCost;
#endif
- (BOOL) todayCostIsSet;

#if !__has_feature(objc_arc)
- (double) todayWin;
- (void) setTodayWin: (double) todayWin;
#endif
- (BOOL) todayWinIsSet;

#if !__has_feature(objc_arc)
- (int32_t) score;
- (void) setScore: (int32_t) score;
#endif
- (BOOL) scoreIsSet;

#if !__has_feature(objc_arc)
- (int32_t) msgNum;
- (void) setMsgNum: (int32_t) msgNum;
#endif
- (BOOL) msgNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) key;
- (void) setKey: (NSString *) key;
#endif
- (BOOL) keyIsSet;

@end

@interface LoginRespBean : NSObject <TBase, NSCoding> {
  Result * __result;
  UserBean * __userBean;

  BOOL __result_isset;
  BOOL __userBean_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, retain, getter=userBean, setter=setUserBean:) UserBean * userBean;
#endif

- (id) init;
- (id) initWithResult: (Result *) result userBean: (UserBean *) userBean;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (UserBean *) userBean;
- (void) setUserBean: (UserBean *) userBean;
#endif
- (BOOL) userBeanIsSet;

@end

@interface VerifyCodeRespBean : NSObject <TBase, NSCoding> {
  Result * __result;
  NSString * __imgData;

  BOOL __result_isset;
  BOOL __imgData_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, retain, getter=imgData, setter=setImgData:) NSString * imgData;
#endif

- (id) init;
- (id) initWithResult: (Result *) result imgData: (NSString *) imgData;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (NSString *) imgData;
- (void) setImgData: (NSString *) imgData;
#endif
- (BOOL) imgDataIsSet;

@end

@interface NewsBean : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __title;
  NSString * __content;
  NSString * __url;
  NSString * __pic;

  BOOL __id_isset;
  BOOL __title_isset;
  BOOL __content_isset;
  BOOL __url_isset;
  BOOL __pic_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, retain, getter=url, setter=setUrl:) NSString * url;
@property (nonatomic, retain, getter=pic, setter=setPic:) NSString * pic;
#endif

- (id) init;
- (id) initWithId: (int32_t) id title: (NSString *) title content: (NSString *) content url: (NSString *) url pic: (NSString *) pic;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content;
- (void) setContent: (NSString *) content;
#endif
- (BOOL) contentIsSet;

#if !__has_feature(objc_arc)
- (NSString *) url;
- (void) setUrl: (NSString *) url;
#endif
- (BOOL) urlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pic;
- (void) setPic: (NSString *) pic;
#endif
- (BOOL) picIsSet;

@end

@interface NewsListRespBean : NSObject <TBase, NSCoding> {
  Result * __result;
  int32_t __total;
  NSMutableArray * __newsList;

  BOOL __result_isset;
  BOOL __total_isset;
  BOOL __newsList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, getter=total, setter=setTotal:) int32_t total;
@property (nonatomic, retain, getter=newsList, setter=setNewsList:) NSMutableArray * newsList;
#endif

- (id) init;
- (id) initWithResult: (Result *) result total: (int32_t) total newsList: (NSMutableArray *) newsList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (int32_t) total;
- (void) setTotal: (int32_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) newsList;
- (void) setNewsList: (NSMutableArray *) newsList;
#endif
- (BOOL) newsListIsSet;

@end

@interface HomeRespBean : NSObject <TBase, NSCoding> {
  Result * __result;
  NSMutableArray * __scrollNewsList;
  NSMutableArray * __winsList;
  NSMutableArray * __newsList;

  BOOL __result_isset;
  BOOL __scrollNewsList_isset;
  BOOL __winsList_isset;
  BOOL __newsList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, retain, getter=scrollNewsList, setter=setScrollNewsList:) NSMutableArray * scrollNewsList;
@property (nonatomic, retain, getter=winsList, setter=setWinsList:) NSMutableArray * winsList;
@property (nonatomic, retain, getter=newsList, setter=setNewsList:) NSMutableArray * newsList;
#endif

- (id) init;
- (id) initWithResult: (Result *) result scrollNewsList: (NSMutableArray *) scrollNewsList winsList: (NSMutableArray *) winsList newsList: (NSMutableArray *) newsList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) scrollNewsList;
- (void) setScrollNewsList: (NSMutableArray *) scrollNewsList;
#endif
- (BOOL) scrollNewsListIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) winsList;
- (void) setWinsList: (NSMutableArray *) winsList;
#endif
- (BOOL) winsListIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) newsList;
- (void) setNewsList: (NSMutableArray *) newsList;
#endif
- (BOOL) newsListIsSet;

@end

@interface BuyBean : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __expect;
  NSString * __protype;
  NSString * __lotterytype;
  NSString * __lotteryid;
  double __mainpaymoney;
  double __allmoney;
  int32_t __anumber;
  double __onemoney;
  NSString * __username;
  int32_t __hnumber;
  double __schedule;
  NSString * __prostate;
  NSString * __codes;
  int32_t __isbaodi;
  int32_t __baodinum;
  NSString * __object;
  NSString * __addtime;
  int32_t __isreturn;
  NSString * __wininfo;
  double __wincost;
  NSString * __beishu;
  NSString * __mystate;
  int32_t __allperson;
  NSString * __lottery_id;
  NSString * __winlevels;
  int32_t __isshow;
  int32_t __ishm;
  NSString * __isjz;
  int32_t __isthew;
  int32_t __tcSelect;
  NSString * __caseInfo;

  BOOL __id_isset;
  BOOL __expect_isset;
  BOOL __protype_isset;
  BOOL __lotterytype_isset;
  BOOL __lotteryid_isset;
  BOOL __mainpaymoney_isset;
  BOOL __allmoney_isset;
  BOOL __anumber_isset;
  BOOL __onemoney_isset;
  BOOL __username_isset;
  BOOL __hnumber_isset;
  BOOL __schedule_isset;
  BOOL __prostate_isset;
  BOOL __codes_isset;
  BOOL __isbaodi_isset;
  BOOL __baodinum_isset;
  BOOL __object_isset;
  BOOL __addtime_isset;
  BOOL __isreturn_isset;
  BOOL __wininfo_isset;
  BOOL __wincost_isset;
  BOOL __beishu_isset;
  BOOL __mystate_isset;
  BOOL __allperson_isset;
  BOOL __lottery_id_isset;
  BOOL __winlevels_isset;
  BOOL __isshow_isset;
  BOOL __ishm_isset;
  BOOL __isjz_isset;
  BOOL __isthew_isset;
  BOOL __tcSelect_isset;
  BOOL __caseInfo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=expect, setter=setExpect:) NSString * expect;
@property (nonatomic, retain, getter=protype, setter=setProtype:) NSString * protype;
@property (nonatomic, retain, getter=lotterytype, setter=setLotterytype:) NSString * lotterytype;
@property (nonatomic, retain, getter=lotteryid, setter=setLotteryid:) NSString * lotteryid;
@property (nonatomic, getter=mainpaymoney, setter=setMainpaymoney:) double mainpaymoney;
@property (nonatomic, getter=allmoney, setter=setAllmoney:) double allmoney;
@property (nonatomic, getter=anumber, setter=setAnumber:) int32_t anumber;
@property (nonatomic, getter=onemoney, setter=setOnemoney:) double onemoney;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, getter=hnumber, setter=setHnumber:) int32_t hnumber;
@property (nonatomic, getter=schedule, setter=setSchedule:) double schedule;
@property (nonatomic, retain, getter=prostate, setter=setProstate:) NSString * prostate;
@property (nonatomic, retain, getter=codes, setter=setCodes:) NSString * codes;
@property (nonatomic, getter=isbaodi, setter=setIsbaodi:) int32_t isbaodi;
@property (nonatomic, getter=baodinum, setter=setBaodinum:) int32_t baodinum;
@property (nonatomic, retain, getter=object, setter=setObject:) NSString * object;
@property (nonatomic, retain, getter=addtime, setter=setAddtime:) NSString * addtime;
@property (nonatomic, getter=isreturn, setter=setIsreturn:) int32_t isreturn;
@property (nonatomic, retain, getter=wininfo, setter=setWininfo:) NSString * wininfo;
@property (nonatomic, getter=wincost, setter=setWincost:) double wincost;
@property (nonatomic, retain, getter=beishu, setter=setBeishu:) NSString * beishu;
@property (nonatomic, retain, getter=mystate, setter=setMystate:) NSString * mystate;
@property (nonatomic, getter=allperson, setter=setAllperson:) int32_t allperson;
@property (nonatomic, retain, getter=lottery_id, setter=setLottery_id:) NSString * lottery_id;
@property (nonatomic, retain, getter=winlevels, setter=setWinlevels:) NSString * winlevels;
@property (nonatomic, getter=isshow, setter=setIsshow:) int32_t isshow;
@property (nonatomic, getter=ishm, setter=setIshm:) int32_t ishm;
@property (nonatomic, retain, getter=isjz, setter=setIsjz:) NSString * isjz;
@property (nonatomic, getter=isthew, setter=setIsthew:) int32_t isthew;
@property (nonatomic, getter=tcSelect, setter=setTcSelect:) int32_t tcSelect;
@property (nonatomic, retain, getter=caseInfo, setter=setCaseInfo:) NSString * caseInfo;
#endif

- (id) init;
- (id) initWithId: (int32_t) id expect: (NSString *) expect protype: (NSString *) protype lotterytype: (NSString *) lotterytype lotteryid: (NSString *) lotteryid mainpaymoney: (double) mainpaymoney allmoney: (double) allmoney anumber: (int32_t) anumber onemoney: (double) onemoney username: (NSString *) username hnumber: (int32_t) hnumber schedule: (double) schedule prostate: (NSString *) prostate codes: (NSString *) codes isbaodi: (int32_t) isbaodi baodinum: (int32_t) baodinum object: (NSString *) object addtime: (NSString *) addtime isreturn: (int32_t) isreturn wininfo: (NSString *) wininfo wincost: (double) wincost beishu: (NSString *) beishu mystate: (NSString *) mystate allperson: (int32_t) allperson lottery_id: (NSString *) lottery_id winlevels: (NSString *) winlevels isshow: (int32_t) isshow ishm: (int32_t) ishm isjz: (NSString *) isjz isthew: (int32_t) isthew tcSelect: (int32_t) tcSelect caseInfo: (NSString *) caseInfo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) expect;
- (void) setExpect: (NSString *) expect;
#endif
- (BOOL) expectIsSet;

#if !__has_feature(objc_arc)
- (NSString *) protype;
- (void) setProtype: (NSString *) protype;
#endif
- (BOOL) protypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lotterytype;
- (void) setLotterytype: (NSString *) lotterytype;
#endif
- (BOOL) lotterytypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lotteryid;
- (void) setLotteryid: (NSString *) lotteryid;
#endif
- (BOOL) lotteryidIsSet;

#if !__has_feature(objc_arc)
- (double) mainpaymoney;
- (void) setMainpaymoney: (double) mainpaymoney;
#endif
- (BOOL) mainpaymoneyIsSet;

#if !__has_feature(objc_arc)
- (double) allmoney;
- (void) setAllmoney: (double) allmoney;
#endif
- (BOOL) allmoneyIsSet;

#if !__has_feature(objc_arc)
- (int32_t) anumber;
- (void) setAnumber: (int32_t) anumber;
#endif
- (BOOL) anumberIsSet;

#if !__has_feature(objc_arc)
- (double) onemoney;
- (void) setOnemoney: (double) onemoney;
#endif
- (BOOL) onemoneyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) hnumber;
- (void) setHnumber: (int32_t) hnumber;
#endif
- (BOOL) hnumberIsSet;

#if !__has_feature(objc_arc)
- (double) schedule;
- (void) setSchedule: (double) schedule;
#endif
- (BOOL) scheduleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) prostate;
- (void) setProstate: (NSString *) prostate;
#endif
- (BOOL) prostateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) codes;
- (void) setCodes: (NSString *) codes;
#endif
- (BOOL) codesIsSet;

#if !__has_feature(objc_arc)
- (int32_t) isbaodi;
- (void) setIsbaodi: (int32_t) isbaodi;
#endif
- (BOOL) isbaodiIsSet;

#if !__has_feature(objc_arc)
- (int32_t) baodinum;
- (void) setBaodinum: (int32_t) baodinum;
#endif
- (BOOL) baodinumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) object;
- (void) setObject: (NSString *) object;
#endif
- (BOOL) objectIsSet;

#if !__has_feature(objc_arc)
- (NSString *) addtime;
- (void) setAddtime: (NSString *) addtime;
#endif
- (BOOL) addtimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) isreturn;
- (void) setIsreturn: (int32_t) isreturn;
#endif
- (BOOL) isreturnIsSet;

#if !__has_feature(objc_arc)
- (NSString *) wininfo;
- (void) setWininfo: (NSString *) wininfo;
#endif
- (BOOL) wininfoIsSet;

#if !__has_feature(objc_arc)
- (double) wincost;
- (void) setWincost: (double) wincost;
#endif
- (BOOL) wincostIsSet;

#if !__has_feature(objc_arc)
- (NSString *) beishu;
- (void) setBeishu: (NSString *) beishu;
#endif
- (BOOL) beishuIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mystate;
- (void) setMystate: (NSString *) mystate;
#endif
- (BOOL) mystateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) allperson;
- (void) setAllperson: (int32_t) allperson;
#endif
- (BOOL) allpersonIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lottery_id;
- (void) setLottery_id: (NSString *) lottery_id;
#endif
- (BOOL) lottery_idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) winlevels;
- (void) setWinlevels: (NSString *) winlevels;
#endif
- (BOOL) winlevelsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) isshow;
- (void) setIsshow: (int32_t) isshow;
#endif
- (BOOL) isshowIsSet;

#if !__has_feature(objc_arc)
- (int32_t) ishm;
- (void) setIshm: (int32_t) ishm;
#endif
- (BOOL) ishmIsSet;

#if !__has_feature(objc_arc)
- (NSString *) isjz;
- (void) setIsjz: (NSString *) isjz;
#endif
- (BOOL) isjzIsSet;

#if !__has_feature(objc_arc)
- (int32_t) isthew;
- (void) setIsthew: (int32_t) isthew;
#endif
- (BOOL) isthewIsSet;

#if !__has_feature(objc_arc)
- (int32_t) tcSelect;
- (void) setTcSelect: (int32_t) tcSelect;
#endif
- (BOOL) tcSelectIsSet;

#if !__has_feature(objc_arc)
- (NSString *) caseInfo;
- (void) setCaseInfo: (NSString *) caseInfo;
#endif
- (BOOL) caseInfoIsSet;

@end

@interface BuyListRespBean : NSObject <TBase, NSCoding> {
  Result * __result;
  int32_t __total;
  NSMutableArray * __buyList;

  BOOL __result_isset;
  BOOL __total_isset;
  BOOL __buyList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, getter=total, setter=setTotal:) int32_t total;
@property (nonatomic, retain, getter=buyList, setter=setBuyList:) NSMutableArray * buyList;
#endif

- (id) init;
- (id) initWithResult: (Result *) result total: (int32_t) total buyList: (NSMutableArray *) buyList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (int32_t) total;
- (void) setTotal: (int32_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) buyList;
- (void) setBuyList: (NSMutableArray *) buyList;
#endif
- (BOOL) buyListIsSet;

@end

@interface RecordWinCode : NSObject <TBase, NSCoding> {
  NSString * __issue;
  NSString * __datetime;
  NSString * __code;

  BOOL __issue_isset;
  BOOL __datetime_isset;
  BOOL __code_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=issue, setter=setIssue:) NSString * issue;
@property (nonatomic, retain, getter=datetime, setter=setDatetime:) NSString * datetime;
@property (nonatomic, retain, getter=code, setter=setCode:) NSString * code;
#endif

- (id) init;
- (id) initWithIssue: (NSString *) issue datetime: (NSString *) datetime code: (NSString *) code;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) issue;
- (void) setIssue: (NSString *) issue;
#endif
- (BOOL) issueIsSet;

#if !__has_feature(objc_arc)
- (NSString *) datetime;
- (void) setDatetime: (NSString *) datetime;
#endif
- (BOOL) datetimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) code;
- (void) setCode: (NSString *) code;
#endif
- (BOOL) codeIsSet;

@end

@interface RecordWinCodeListResp : NSObject <TBase, NSCoding> {
  Result * __result;
  int32_t __total;
  NSMutableArray * __recordList;

  BOOL __result_isset;
  BOOL __total_isset;
  BOOL __recordList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) Result * result;
@property (nonatomic, getter=total, setter=setTotal:) int32_t total;
@property (nonatomic, retain, getter=recordList, setter=setRecordList:) NSMutableArray * recordList;
#endif

- (id) init;
- (id) initWithResult: (Result *) result total: (int32_t) total recordList: (NSMutableArray *) recordList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Result *) result;
- (void) setResult: (Result *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (int32_t) total;
- (void) setTotal: (int32_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) recordList;
- (void) setRecordList: (NSMutableArray *) recordList;
#endif
- (BOOL) recordListIsSet;

@end

@protocol UappService <NSObject>
- (LoginRespBean *) login: (NSString *) loginName pwd: (NSString *) pwd timestamp: (NSString *) timestamp verifyCode: (NSString *) verifyCode deviceId: (NSString *) deviceId loginType: (int32_t) loginType;  // throws TException
- (Result *) logout: (NSString *) key;  // throws TException
- (VerifyCodeRespBean *) getVerifyCode: (NSString *) deviceId;  // throws TException
- (NewsListRespBean *) getScrollNewsList: (int32_t) limit;  // throws TException
- (NewsListRespBean *) getNewsList: (int32_t) page rows: (int32_t) rows;  // throws TException
- (HomeRespBean *) getHome: (NSString *) deviceId;  // throws TException
- (LoginRespBean *) getUserInfo: (NSString *) key;  // throws TException
- (BuyListRespBean *) getBuyList: (NSString *) key type: (NSString *) type page: (int32_t) page rows: (int32_t) rows;  // throws TException
- (Result *) doBuy: (NSString *) key codes: (NSString *) codes jsonParams: (NSString *) jsonParams;  // throws TException
- (BuyListRespBean *) getWinBuyList: (NSString *) name rows: (int32_t) rows;  // throws TException
- (RecordWinCodeListResp *) getWinCodesById: (NSString *) id;  // throws TException
- (RecordWinCodeListResp *) getRecordWinCodeList: (NSString *) type;  // throws TException
@end

@interface UappServiceClient : NSObject <UappService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UappServiceProcessor : NSObject <TProcessor> {
  id <UappService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUappService: (id <UappService>) service;
- (id<UappService>) service;
@end

@interface uappConstants : NSObject {
}
@end
